function options() {
    for(let x = 1;x <= 2; x++) {
        for(const moeda in moedas){
            if(document.querySelector('.par'+ x)){
                select = document.querySelector('.par'+ x)
                let d = document.createElement('option')
                d.setAttribute('value', moeda)
                select.appendChild(d)
                let text = document.createTextNode(moedas[moeda])
                d.appendChild(text)
            }
        } 
    }
}

const moedas = {
    USD: "USD - Dólar Americano",
    AUD: "AUD - Dólar Australiano",
    CAD: "CAD - Dólar Canadense",
    BRL: "BRL - Real Brasileiro",
    BRLT: "RLT - Real Brasileiro Turismo",
    JPY: "JPY - Iene Japonês",
    EUR: "EUR - Euro",
    CHF: "CHF - Franco Suíço",
    BZD: "BZD - Dólar de Belize",
    BND: "BND - Dólar de Brunei",
    SGD: "SGD - Dólar de Cingapura",
    FJD: "FJD - Dólar de Fiji",
    HKD: "HKD - Dólar de Hong Kong",
    TTD: "TTD - Dólar de Trinidad",
    XCD: "XCD - Dólar do Caribe Oriental",
    CVE: "CVE - Escudo cabo-verdiano",
    THB: "THB - Baht Tailandês",
    PAB: "PAB - Balboa Panamenho",
    ETB: "ETB - Birr Etíope",
    BTC: "BTC - Bitcoin",
    BOB: "BOB - Boliviano",
    VEF: "VEF - Bolívar Venezuelano",
    XBR: "XBR - Brent Spot",
    GHS: "GHS - Cedi Ganês",
    SVC: "SVC - Colon de El Salvador",
    CRC: "CRC - Colón Costarriquenho",
    CZK: "CZK - Coroa Checa",
    DKK: "DKK - Coroa Dinamarquesa",
    ISK: "ISK - Coroa Islandesa",
    NOK: "NOK - Coroa Norueguesa",
    SEK: "SEK - Coroa Sueca",
    NIO: "NIO - Córdoba Nicaraguense",
    SDR: "SDR - DSE",
    GMD: "GMD - Dalasi da Gâmbia",
    MKD: "MKD - Denar Macedônio",
    DZD: "DZD - Dinar Argelino",
    JOD: "JOD - Dinar Jordaniano",
    KWD: "KWD - Dinar Kuwaitiano",
    LYD: "LYD - Dinar Líbio",
    RSD: "RSD - Dinar Sérvio",
    TND: "TND - Dinar Tunisiano",
    BHD: "BHD - Dinar do Bahrein",
    MAD: "MAD - Dirham Marroquino",
    AED: "AED - Dirham dos Emirados",
    STD: "STD - Dobra São Tomé/Príncipe",
    DOGE: "OGE - Dogecoin",
    VND: "VND - Dong Vietnamita",
    AMD: "AMD - Dram Armênio",
    JMD: "JMD - Dólar Jamaicano",
    NAD: "NAD - Dólar Namíbio",
    AFN: "AFN - Afghani do Afeganistão",
    MGA: "MGA - Ariary Madagascarense",
    NZD: "NZD - Dólar Neozelandês",
    TWD: "TWD - Dólar Taiuanês",
    ZWL: "ZWL - Dólar Zimbabuense",
    BSD: "BSD - Dólar das Bahamas",
    KYD: "KYD - Dólar das Ilhas Cayman",
    BBD: "BBD - Dólar de Barbados",
    ETH: "ETH - Ethereum",
    HUF: "HUF - Florim Húngaro",
    BIF: "BIF - Franco Burundinense",
    XAF: "XAF - Franco CFA Central",
    XOF: "XOF - Franco CFA Ocidental",
    XPF: "XPF - Franco CFP",
    KMF: "KMF - Franco Comorense",
    RWF: "RWF - Franco Ruandês",
    RTS: "RTS - Franco Suíço",
    GNF: "GNF - Franco de Guiné",
    DJF: "DJF - Franco do Djubouti",
    HTG: "HTG - Gourde Haitiano",
    PYG: "PYG - Guarani Paraguaio",
    ANG: "ANG - Guilder das Antilhas",
    UAH: "UAH - Hryvinia Ucraniana",
    JPY: "JPY - Iene Japonês",
    PGK: "PGK - Kina Papua-Nova Guiné",
    LAK: "LAK - Kip Laosiano",
    HRK: "HRK - Kuna Croata",
    MWK: "MWK - Kwacha Malauiana",
    ZMK: "ZMK - Kwacha Zambiana",
    AOA: "AOA - Kwanza Angolano",
    MMK: "MMK - Kyat de Mianmar",
    GEL: "GEL - Lari Georgiano",
    ALL: "ALL - Lek Albanês",
    HNL: "HNL - Lempira Hondurenha",
    MDL: "MDL - Leu Moldavo",
    RON: "RON - Leu Romeno",
    BGN: "BGN - Lev Búlgaro",
    EGP: "EGP - Libra Egípcia",
    GBP: "GBP - Libra Esterlina",
    LBP: "LBP - Libra Libanesa",
    SDG: "SDG - Libra Sudanesa",
    SYP: "SYP - Libra Síria",
    SZL: "SZL - Lilangeni Suazilandês",
    LTC: "LTC - Litecoin",
    LSL: "LSL - Loti do Lesoto",
    AZN: "AZN - Manat Azeri",
    BAM: "BAM - Marco Conversível",
    MZN: "MZN - Metical de Moçambique",
    MNT: "MNT - Mongolian Tugrik",
    NGN: "LEL - Naira Nigeriana",
    NGN: "NGN - Naira Nigeriana",
    NGNI: "GNI - Naira Nigeriana",
    TRY: "TRY - Nova Lira Turca",
    ILS: "ILS - Novo Shekel Israelense",
    MRO: "MRO - Ouguiya Mauritana",
    MOP: "MOP - Pataca de Macau",
    ARS: "ARS - Peso Argentino",
    CLP: "CLP - Peso Chileno",
    COP: "COP - Peso Colombiano",
    CUP: "CUP - Peso Cubano",
    DOP: "DOP - Peso Dominicano",
    PHP: "PHP - Peso Filipino",
    MXN: "MXN - Peso Mexicano",
    UYU: "UYU - Peso Uruguaio",
    BWP: "BWP - Pula de Botswana",
    GTQ: "GTQ - Quetzal Guatemalteco",
    ZAR: "ZAR - Rand Sul-Africano",
    QAR: "QAR - Rial Catarense",
    IRR: "IRR - Rial Iraniano",
    OMR: "OMR - Rial Omanense",
    KHR: "KHR - Riel Cambojano",
    MYR: "MYR - Ringgit Malaio",
    YER: "YER - Riyal Iemenita",
    SAR: "SAR - Riyal Saudita",
    BYN: "BYN - Rublo Bielorrusso",
    RUB: "TOM - Rublo Russo",
    RUB: "RUB - Rublo Russo",
    MVR: "MVR - Rufiyaa Maldiva",
    IDR: "IDR - Rupia Indonésia",
    INR: "INR - Rúpia Indiana",
    MUR: "MUR - Rúpia Mauriciana",
    NPR: "NPR - Rúpia Nepalesa",
    PKR: "PKR - Rúpia Paquistanesa",
    LKR: "LKR - Rúpia de Sri Lanka",
    SCR: "SCR - Rúpias de Seicheles",
    KES: "KES - Shilling Queniano",
    SOS: "SOS - Shilling Somaliano",
    TZS: "TZS - Shilling Tanzaniano",
    UGX: "UGX - Shilling Ugandês",
    PEN: "PEN - Sol do Peru",
    KGS: "KGS - Som Quirguistanês",
    UZS: "UZS - Som Uzbequistanês",
    TJS: "TJS - Somoni do Tajiquistão",
    TMT: "TMT - TMT",
    BDT: "BDT - Taka de Bangladesh",
    KZT: "KZT - Tengue Cazaquistanês",
    VUV: "VUV - Vatu de Vanuatu",
    KRW: "KRW - Won Sul-Coreano",
    XAGG: "AGG - XPrata",
    XRP: "XRP - XRP",
    CNY: "CNY - Yuan Chinês",
    CNH: "CNH - Yuan chinês offshore",
    PLN: "PLN - Zlóti Polonês",
}